### ISSUE TITLE
meshcat-server command not working 

### ISSUE THREAD

**Issue by rickyduh** [rdeits/meshcat-python#30]
Whenever I run meshcat-server, the page that opens up says error 404 not found and this is what is displayed in my command window: 
zmq_url=tcp://127.0.0.1:6000
web_url=http://127.0.0.1:7000/static/
Firefox hook launcher starting up
run-parts: executing /usr/lib/amazon/firefox-hooks/00amazon-firefox-certs
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
run-parts: executing /usr/lib/amazon/firefox-hooks/10firefox-disable-bad-prefs
Firefox hook launcher finished
WARNING:tornado.access:404 GET /static/ (127.0.0.1) 1.37ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.33ms

(/usr/lib/firefox/firefox:3427): Gtk-WARNING **: Theme parsing error: gtk-main.css:18:33: Invalid number for color value
^CTraceback (most recent call last):
  File "/usr/local/bin/meshcat-server", line 11, in <module>
    load_entry_point('meshcat==0.0.13', 'console_scripts', 'meshcat-server')()
  File "/home/me/meshcat/servers/zmqserver.py", line 177, in main
    bridge.run()
  File "/home/me/meshcat/servers/zmqserver.py", line 159, in run
    self.ioloop.start()
  File "/usr/local/lib/python2.7/dist-packages/tornado-5.1.1-py2.7-linux-x86_64.egg/tornado/ioloop.py", line 1048, in start
    event_pairs = self._impl.poll(poll_timeout)

any ideas on this?

**Comment by rickyduh** [comment]
I fixed the issue by running python meshcat-server instead of just meshcat server

**Comment by rdeits** [comment]
The only thing I can think of is that perhaps Firefox is being opened before the server is actually ready. Does refreshing the page have any effect?

**Comment by suvansh** [comment]
I'm facing a similar issue. Here is the output I get from running `meshcat-server`:
```
zmq_url=tcp://127.0.0.1:6000
web_url=http://127.0.0.1:7000/static/
WARNING:tornado.access:404 GET /static/ (127.0.0.1) 1.80ms
```
The last line shows up when I open the URL (http://127.0.0.1:7000/static/). Do you have any thoughts on what may be causing this tornado issue and the 404 error? I get the same issue when I run the demo notebooks.

**Comment by WangXingfang** [comment]
> I'm facing a similar issue. Here is the output I get from running `meshcat-server`:
> 
> ```
> zmq_url=tcp://127.0.0.1:6000
> web_url=http://127.0.0.1:7000/static/
> WARNING:tornado.access:404 GET /static/ (127.0.0.1) 1.80ms
> ```
> 
> The last line shows up when I open the URL (http://127.0.0.1:7000/static/). Do you have any thoughts on what may be causing this tornado issue and the 404 error? I get the same issue when I run the demo notebooks.

I have the same problem as you. Have you solved it ？

**Comment by Arpafaucon** [comment]
> > I'm facing a similar issue. Here is the output I get from running `meshcat-server`:
> > ```
> > zmq_url=tcp://127.0.0.1:6000
> > web_url=http://127.0.0.1:7000/static/
> > WARNING:tornado.access:404 GET /static/ (127.0.0.1) 1.80ms
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The last line shows up when I open the URL (http://127.0.0.1:7000/static/). Do you have any thoughts on what may be causing this tornado issue and the 404 error? I get the same issue when I run the demo notebooks.
> 
> I have the same problem as you. Have you solved it ？

I ran into the same problem when working on submitting a patch for `meshcat-python`: so I had cloned the `meshcat-python` repo and run `pip install .` inside.

The issue was that I had forgotten to checkout the submodules ! `git submodule update --init --recursive` solved the problem for me

**Comment by ZahraAdel** [comment]
I am facing such an error 

RuntimeError: the meshcat server process exited prematurely with exit code 1

what should i do?

**Comment by SUPERCILEX** [comment]
Looks like you can start it with `python -m meshcat.servers.zmqserver`.
